### PR TITLE
add console logging levels, helps debug coding.

### PR DESCRIPTION
**Pull request by andyblac**
Default = 0 (State logging)
```
[10/5/2019, 2:22:16 PM] [Garage Burglar Alarm] New state detected: (3) -> DISARM. Notify!
[10/5/2019, 2:28:46 PM] [Garage Burglar Alarm] Setting state to AWAY_ARM
[10/5/2019, 2:28:53 PM] [Garage Burglar Alarm] New state detected: (1) -> AWAY_ARM. Notify!
```

### CODE REVIEW

**Comment by gawindx** [comment]
I am not going to follow up on your proposal, not because it does not deserve attention, but rather because of the changes I made to the whole code.
I used another approach that seems to me more in sync with the development of 'Homebridge' in the sense that debug level logs are only displayed when debug mode is active.

This does not preclude that for clarity, your approach can allow an increase of plugin logs without being polluted by 'Homebridge' logs so I do not exclude definitively a change to come.

Perhaps it would be easier to apply it to an overloading of the log function itself to avoid scrambling the code unnecessarily.

**Comment by gawindx** [comment]
@andyblac 

I made available the 'platform' version of the plugin.
you can test it but you must first install the 'axios' library, to do this:
* if, like me, you use Homebridge from a Docker container, you must then connect to the container before:
docker exec -ti container_name sh
* go to the plugin directory
cd / homebridge / node_modules / homebridge-risco-alarm
* update the file 'package.json' (copying the content from the branch file 'RiscoPanel-Platforms' otherwise 'axios' will not be installed).
* install in the current directory
npm i --prefix ./ axios

You can then update the different files.

**Comment by andyblac** [comment]
@gawindx I'll give that ago this afternoon, regarding logging, it was to help debugging, when in normal running mode I like to see when the states where changed etc, but when coding I like to see full logs, how are you doing this, or do you not use logs in normal running ?

**Comment by andyblac** [comment]
@gawindx how do I add multiple partitions with your new code ?

**Comment by andyblac** [comment]
@gawindx get this error trying install axios

```
root@soma-connect:/usr/lib/node_modules/homebridge-risco-alarm# npm i --prefix ./ axios
npm ERR! code EJSONPARSE
npm ERR! file /usr/lib/node_modules/homebridge-risco-alarm/package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token ^ in JSON at position 207 while parsing near '....0.2",
npm ERR! JSON.parse     "axios": ^0.19.0
npm ERR! JSON.parse   },
npm ERR! JSON.parse   "engi...'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-19T11_06_56_506Z-debug.log
root@soma-connect:/usr/lib/node_modules/homebridge-risco-alarm# 
```



found issue missing ""  axios line

**Comment by andyblac** [comment]
this git seem to be missing ISSUES tab

ok got it to start, get following error

            "Partition": "all"

```
[10/19/2019, 12:28:26 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 12:28:26 PM] [Home Alarm] Error on Discovery Partition : TypeError: Cannot read property 'parts' of null
[10/19/2019, 12:28:26 PM] [Home Alarm] Discovering Phase Ended
[10/19/2019, 12:28:26 PM] [Home Alarm] AddAccessory Phase Started
[10/19/2019, 12:28:26 PM] [Home Alarm] Error on AddAccessory Phase : TypeError: Cannot read property 'type' of undefined
[10/19/2019, 12:28:26 PM] [Home Alarm] AddAccessory Phase Ended
[10/19/2019, 12:28:26 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 12:28:26 PM] [Home Alarm] Error on Get Partitions States : TypeError: Cannot read property 'type' of undefined
(node:12146) UnhandledPromiseRejectionWarning: undefined
(node:12146) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12146) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by andyblac** [comment]
do you have Skype or something similar so we can chat live ?

**Comment by andyblac** [comment]
"Partition": "0,1"
```
[10/19/2019, 12:56:50 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 12:56:50 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 12:56:50 PM] [Home Alarm] Error on Get Partitions States : TypeError: Cannot read property 'partitions' of undefined
(node:12931) UnhandledPromiseRejectionWarning: undefined
(node:12931) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:12931) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/19/2019, 12:56:50 PM] [Home Alarm] Partition type 0,1
[10/19/2019, 12:56:50 PM] [Home Alarm] req 0,1
[10/19/2019, 12:56:50 PM] [Home Alarm] includes ? true
[10/19/2019, 12:56:50 PM] [Home Alarm] dudu 0
[10/19/2019, 12:56:50 PM] [Home Alarm] dudu 1
[10/19/2019, 12:56:50 PM] [Home Alarm] Partition type 0,1
[10/19/2019, 12:56:50 PM] [Home Alarm] req 0,1
[10/19/2019, 12:56:50 PM] [Home Alarm] includes ? true
[10/19/2019, 12:56:50 PM] [Home Alarm] dudu 0
[10/19/2019, 12:56:50 PM] [Home Alarm] dudu 1
[10/19/2019, 12:56:50 PM] [Home Alarm] Discovered 2 Partitions
[10/19/2019, 12:56:50 PM] [Home Alarm] Discovering Phase Ended
[10/19/2019, 12:56:50 PM] [Home Alarm] AddAccessory Phase Started
[10/19/2019, 12:56:50 PM] [Home Alarm] Create Accessory for Partitions Id : 0 and labeled Castle Int Alarm
[10/19/2019, 12:56:50 PM] [Home Alarm] Create Accessory for Partitions Id : 1 and labeled Garage
[10/19/2019, 12:56:50 PM] [Home Alarm] Initializing platform accessory 'Castle Int Alarm'...
[10/19/2019, 12:56:50 PM] [Home Alarm] Initializing platform accessory 'Garage'...
[10/19/2019, 12:56:51 PM] [Home Alarm] AddAccessory Phase Ended
[10/19/2019, 12:56:51 PM] [Home Alarm] Partition "Castle Int Alarm" => New state detected: (3) -> DISARM. Notify!
[10/19/2019, 12:56:51 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
```

they show in HomeKit, but Arming / Disarming does nothing to the alarm panel.
EDIT: I see thats on todo list ok, np
EDIT2: hmm it seem partition 1 is arming / disarming (garage), but partition 0 (Castle Int Alarm) is not

```
[10/19/2019, 1:28:33 PM] [Home Alarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
[10/19/2019, 1:28:43 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
[10/19/2019, 1:29:13 PM] [Home Alarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
[10/19/2019, 1:29:33 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
[10/19/2019, 1:34:53 PM] [Home Alarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
[10/19/2019, 1:36:13 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
[10/19/2019, 1:36:43 PM] [Home Alarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
[10/19/2019, 1:39:53 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
```

**Comment by andyblac** [comment]
"system": will generate an accessory for each partition

thats incorrect it generates 1 Accessory labeled "Home Alarm".

**Comment by gawindx** [comment]
I will try to answer each point:
- for logs: I do not like being polluted by too much information in normal operation. As for the devellopement, I add the logs that I need to validate the different processes (like the "dudu" that have seen in the last logs that you provided and that I forgot to delete. ..) and I only keep in the final code those that are relevant.
- Installation of Axios: I forgot to add the ", it is corrected.
- for Skype, unless you speak French, we will forget; I can read and understand English (I understand especially the general sense in some cases), google translate helps me to have a written English is about correct but in terms of speaking, I am unable .
- For arming / disarming, this should normally work. On the other hand, I notice that going from partial mode(night or home) to stay mode (or vice versa), does not seem to happen properly
In the logs that you provide, we see an error concerning "Can not read property 'partitions' of undefined". I have already noticed this error and it should definitely disappear when I changed the code to manage several panels.

For now, I advise you to reload Homebridge when you see it appear because it means that the plugin did not correctly retrieve all the information from the plant.

**Comment by andyblac** [comment]
@gawindx I mean text chat live. Skype.

**Comment by andyblac** [comment]
it seems that issue is with partition 0, if I set via my alarm panel you code does not see the change, or can it disarm it, but partition 1 works fine.

**Comment by andyblac** [comment]
@gawindx found the bug look at the differences between arming partition 0 and partition 1

```
[10/19/2019, 2:07:55 PM] [Home Alarm] armDisarm: true CMD: 0armed
[10/19/2019, 2:07:55 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:07:55 PM] [Home Alarm] armDisarm: 200
[10/19/2019, 2:07:55 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:07:55 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:05 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:05 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:11 PM] [Home Alarm] Setting state to 3
[10/19/2019, 2:08:11 PM] [Home Alarm] armDisarm: false CMD: 0disarmed
[10/19/2019, 2:08:11 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:11 PM] [Home Alarm] armDisarm: 200
[10/19/2019, 2:08:15 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:15 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:25 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:25 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:29 PM] [Home Alarm] Setting state to 1
[10/19/2019, 2:08:29 PM] [Home Alarm] armDisarm: true CMD: 1:armed
[10/19/2019, 2:08:29 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:33 PM] [Home Alarm] armDisarm: 200
[10/19/2019, 2:08:33 PM] [Home Alarm] Setting state to 3
[10/19/2019, 2:08:33 PM] [Home Alarm] armDisarm: false CMD: 1:disarmed
[10/19/2019, 2:08:33 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:35 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:35 PM] [Home Alarm] User Code Expired ? false
[10/19/2019, 2:08:36 PM] [Home Alarm] armDisarm: 200
[10/19/2019, 2:08:36 PM] [Home Alarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
```

`[10/19/2019, 2:07:55 PM] [Home Alarm] armDisarm: true CMD: 0armed`
`[10/19/2019, 2:08:29 PM] [Home Alarm] armDisarm: true CMD: 1:armed`

**Comment by andyblac** [comment]
```
[10/19/2019, 2:22:18 PM] [Home Alarm] Setting state to 1
[10/19/2019, 2:22:18 PM] [Home Alarm] RiscoPartId:0
[10/19/2019, 2:22:18 PM] [Home Alarm] separator test 1
[10/19/2019, 2:22:18 PM] [Home Alarm] cmd_separator ""
[10/19/2019, 2:22:18 PM] [Home Alarm] Setting PartId to 0
[10/19/2019, 2:22:18 PM] [Home Alarm] armDisarm: trueCMD: 0armed
```

```
[10/19/2019, 2:22:29 PM] [Home Alarm] Setting state to 1
[10/19/2019, 2:22:29 PM] [Home Alarm] RiscoPartId:1
[10/19/2019, 2:22:29 PM] [Home Alarm] separator test 2
[10/19/2019, 2:22:29 PM] [Home Alarm] cmd_separator ":"
[10/19/2019, 2:22:29 PM] [Home Alarm] Setting PartId to 1
[10/19/2019, 2:22:29 PM] [Home Alarm] armDisarm: trueCMD: 1:armed
[
```

**Comment by andyblac** [comment]
ok changing this line https://github.com/gawindx/homebridge-risco-alarm/blob/RiscoPanel-Platforms/RiscoAccessories.js#L118 to `                if (self.RiscoPartId == null){` fixes the issue, it seems 0 is equal to '' thus no separator is applied.

```
[10/19/2019, 2:28:47 PM] [Home Alarm] Setting state to 1
[10/19/2019, 2:28:47 PM] [Home Alarm] RiscoPartId:0
[10/19/2019, 2:28:47 PM] [Home Alarm] separator test 2
[10/19/2019, 2:28:47 PM] [Home Alarm] cmd_separator ":"
[10/19/2019, 2:28:47 PM] [Home Alarm] Setting PartId to 0
[10/19/2019, 2:28:47 PM] [Home Alarm] armDisarm: trueCMD: 0:armed
[10/19/2019, 2:29:41 PM] [Home Alarm] Partition "Castle Int Alarm" => New state detected: (1) -> AWAY_ARM. Notify!
```

**Comment by gawindx** [comment]
Well seen.
But this only corrects the problem in the case of partition mode.
In the case of the system mode, this generates a new problem.

I made some other changes to 'RiscoAccessries.js' to fix the problem.

**Comment by andyblac** [comment]
look at my pull request :), imo it's cleaner than your new code.

EDIT:
oh I see, setting all partitions with `system` ok good catch too :)

have you looked at 'all' dose not seem to work for me.

**Comment by andyblac** [comment]
still an error on start up

```
[10/19/2019, 3:16:32 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 3:16:32 PM] [Home Alarm] Logged In Cloud
[10/19/2019, 3:16:32 PM] [Home Alarm] Error on Get Partitions States : TypeError: Cannot read property 'partitions' of undefined
(node:16331) UnhandledPromiseRejectionWarning: undefined
(node:16331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:16331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10/19/2019, 3:16:32 PM] [Home Alarm] Discovered 2 Partitions
[10/19/2019, 3:16:32 PM] [Home Alarm] Discovering Phase Ended
[10/19/2019, 3:16:32 PM] [Home Alarm] AddAccessory Phase Started
[10/19/2019, 3:16:32 PM] [Home Alarm] Create Accessory for Partitions Id : 0 and labeled Castle Int Alarm
[10/19/2019, 3:16:32 PM] [Home Alarm] Create Accessory for Partitions Id : 1 and labeled Garage
[10/19/2019, 3:16:32 PM] [Home Alarm] Initializing platform accessory 'Castle Int Alarm'...
[10/19/2019, 3:16:32 PM] [Home Alarm] Initializing platform accessory 'Garage'...
[10/19/2019, 3:16:32 PM] [Home Alarm] AddAccessory Phase Ended
[10/19/2019, 3:16:33 PM] Homebridge is running on port 51826.
[10/19/2019, 3:16:33 PM] [Home Alarm] Partition "Castle Int Alarm" => New state detected: (3) -> DISARM. Notify!
[10/19/2019, 3:16:33 PM] [Home Alarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
```

**Comment by gawindx** [comment]
I did not see you request before.
And little has we had the same approach.
I got some of your code simpler than mine and I added it.

The startup error is caused by the fact that the accessories are not yet all discovered when the session is initialized.
But this problem does not block homebridge and should disappear when I modified the code to allow the use of several Panels.

For the moment, I would like the plugin to work at least as well as the 'accessories' version before adding more function. Otherwise it could be a nice mess to debug.

**Comment by andyblac** [comment]
with the last commit `all` now appears to be working, and startup with no errors.

why does this GitHub have no issue tab ? so I can report issues better ?

**Comment by gawindx** [comment]
It seems like it's because it's a fork.
I do not see tab 'issue' on your fork either.

**Comment by andyblac** [comment]
found it:

Go to the Settings page of your fork.
Check the box next to Issues

Screenshot 2019-10-19 at 18 10 42

**Comment by andyblac** [comment]
getting some errors
```
[10/20/2019, 12:34:29 PM] [RiscoAlarm] Partition "Garage" => New state detected: (3) -> DISARM. Notify!
[10/20/2019, 12:34:30 PM] [RiscoAlarm] Error on Get Partitions States : TypeError: Cannot read property 'parts' of null
(node:19521) UnhandledPromiseRejectionWarning: undefined
(node:19521) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 102)
[10/20/2019, 12:34:40 PM] [RiscoAlarm] Session Expired. ReLogin
[10/20/2019, 12:34:40 PM] [RiscoAlarm] Logged In Cloud
[10/20/2019, 12:52:29 PM] [RiscoAlarm] Partition "Garage" => New state detected: (1) -> AWAY_ARM. Notify!
```

I have switched Homebridge to debug mode `-D` see if it give more info.

**Pull request closed without merging**
